/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignsHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author forumkaria
 */
public
        class CreateJPanel extends javax.swing.JPanel {
        private Application application;

    /**
     * Creates new form CreateJPanel
     */
    public
            CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
          initComponents();
          
          this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TemperatureField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BloodPressurefield = new javax.swing.JTextField();
        observationIDField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addObservtionBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CREATE A VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 140, 30));

        TemperatureField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperatureFieldActionPerformed(evt);
            }
        });
        add(TemperatureField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 150, -1));

        jLabel2.setText("Temperature");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        BloodPressurefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodPressurefieldActionPerformed(evt);
            }
        });
        add(BloodPressurefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 150, -1));

        observationIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observationIDFieldActionPerformed(evt);
            }
        });
        add(observationIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, -1));

        jLabel3.setText("Blood Pressure");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel5.setText("ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 126, 20, 20));

        addObservtionBtn.setText("ADD OBSERVATION");
        addObservtionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObservtionBtnActionPerformed(evt);
            }
        });
        add(addObservtionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TemperatureFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperatureFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemperatureFieldActionPerformed

    private void BloodPressurefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodPressurefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodPressurefieldActionPerformed

    private void observationIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observationIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observationIDFieldActionPerformed

    private void addObservtionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObservtionBtnActionPerformed
        // TODO add your handling code here:
        
        VitalSignsHistory history = this.application.getHistory();
        
        String id = observationIDField.getText();
        String temperature = TemperatureField.getText();
        String bloodPressure = BloodPressurefield.getText();
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(temperature), Double.valueOf(bloodPressure) );
        
        JOptionPane.showMessageDialog(null, "Added Observation");
    }//GEN-LAST:event_addObservtionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodPressurefield;
    private javax.swing.JTextField TemperatureField;
    private javax.swing.JButton addObservtionBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField observationIDField;
    // End of variables declaration//GEN-END:variables
}
