/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author forumkaria
 */
public
        class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private
            DeliveryPackage delPackage;

    private
            Boolean validate = false;

    public
            CreateJPanel() {
        initComponents();
    }

    CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();

        this.delPackage = deliveryPackage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        prodIDJLabel = new javax.swing.JLabel();
        prodPriceTxtField = new javax.swing.JTextField();
        prodPriceJLabel = new javax.swing.JLabel();
        prodIDTxtField = new javax.swing.JTextField();
        prodNameJLabel = new javax.swing.JLabel();
        prodNameTxtField = new javax.swing.JTextField();
        saveProductJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        custIDJLabel = new javax.swing.JLabel();
        custIDTxtField = new javax.swing.JTextField();
        custNameJLabel = new javax.swing.JLabel();
        custNameTxtField = new javax.swing.JTextField();
        packageIDJLabel = new javax.swing.JLabel();
        packageIDTxtField = new javax.swing.JTextField();
        packageWeightJLabel = new javax.swing.JLabel();
        packageWeightTxtField = new javax.swing.JTextField();
        saveJButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        prodIDJLabel.setText("Product ID");

        prodPriceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodPriceTxtFieldActionPerformed(evt);
            }
        });

        prodPriceJLabel.setText("Product Price");

        prodIDTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodIDTxtFieldFocusLost(evt);
            }
        });
        prodIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodIDTxtFieldActionPerformed(evt);
            }
        });

        prodNameJLabel.setText("Product Name");

        prodNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodNameTxtFieldActionPerformed(evt);
            }
        });

        saveProductJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        saveProductJButton.setText("SAVE PRODUCT");
        saveProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodPriceJLabel)
                    .addComponent(prodIDJLabel)
                    .addComponent(prodNameJLabel))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(prodPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveProductJButton)
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIDJLabel)
                    .addComponent(prodIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNameJLabel)
                    .addComponent(prodNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodPriceJLabel)
                    .addComponent(prodPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(saveProductJButton)
                .addGap(117, 117, 117))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        custIDJLabel.setText("Customer ID");

        custIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTxtFieldActionPerformed(evt);
            }
        });

        custNameJLabel.setText("Customer Name");

        custNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custNameTxtFieldFocusLost(evt);
            }
        });
        custNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTxtFieldActionPerformed(evt);
            }
        });

        packageIDJLabel.setText("Package ID");

        packageIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageIDTxtFieldActionPerformed(evt);
            }
        });

        packageWeightJLabel.setText("Package Weight");

        packageWeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightTxtFieldActionPerformed(evt);
            }
        });

        saveJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        saveJButton.setText("SAVE");
        saveJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(custNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(packageWeightJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(packageWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(packageIDJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(packageIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(custIDJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(saveJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIDJLabel)
                    .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custNameJLabel)
                    .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageIDJLabel)
                    .addComponent(packageIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageWeightJLabel)
                    .addComponent(packageWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(saveJButton)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
                         
    
    private void custIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTxtFieldActionPerformed

    private void custNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTxtFieldActionPerformed

    private void packageIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageIDTxtFieldActionPerformed

    private void packageWeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightTxtFieldActionPerformed

    private void prodPriceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodPriceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodPriceTxtFieldActionPerformed

    private void prodIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodIDTxtFieldActionPerformed

    private void prodNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNameTxtFieldActionPerformed

    private void prodIDTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodIDTxtFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_prodIDTxtFieldFocusLost

    private void custNameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameTxtFieldFocusLost
        // TODO add your handling code here:
        System.out.println(custNameTxtField.getText() + " -- the customer name");
        String name = custNameTxtField.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_custNameTxtFieldFocusLost

    private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJButtonActionPerformed
        // TODO add your handling code here:
        // get the data
        String id = packageIDTxtField.getText();
        String weight = packageWeightTxtField.getText();
        
        String customerId = custIDTxtField.getText();
        String customername = custNameTxtField.getText();
        
        
        
        // store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
     
        Customer customer = this.delPackage.getCustomer();
        customer.setCustId(Integer.valueOf(customerId));
        customer.setFullName(customername);
        
        if(validate) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
        
        
    }//GEN-LAST:event_saveJButtonActionPerformed

    private void saveProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductJButtonActionPerformed
        // TODO add your handling code here:
try{
            String productId = prodIDTxtField.getText();
        
        String productName = prodNameTxtField.getText();
        String productPrice = prodPriceTxtField.getText();
            if(productId.length()==0 || productName.length()==0 || productPrice.length()==0 ){
            System.out.println("Empty values not accepted.");
            }
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
       
        JOptionPane.showMessageDialog(null, "Added Product");
        }catch (Exception e) {
      System.out.println("Product ID must be a number." + e);
    }    
    
    }//GEN-LAST:event_saveProductJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custIDJLabel;
    private javax.swing.JTextField custIDTxtField;
    private javax.swing.JLabel custNameJLabel;
    private javax.swing.JTextField custNameTxtField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel packageIDJLabel;
    private javax.swing.JTextField packageIDTxtField;
    private javax.swing.JLabel packageWeightJLabel;
    private javax.swing.JTextField packageWeightTxtField;
    private javax.swing.JLabel prodIDJLabel;
    private javax.swing.JTextField prodIDTxtField;
    private javax.swing.JLabel prodNameJLabel;
    private javax.swing.JTextField prodNameTxtField;
    private javax.swing.JLabel prodPriceJLabel;
    private javax.swing.JTextField prodPriceTxtField;
    private javax.swing.JButton saveJButton;
    private javax.swing.JButton saveProductJButton;
    // End of variables declaration//GEN-END:variables
}
