/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author forumkaria
 */
public class EditJPanel extends javax.swing.JPanel {

    private DeliveryPackage delPackage;
    private Product productViewed;

    /**
     * Creates new form EditJPanel
     */
    public EditJPanel() {
        initComponents();
    }

    EditJPanel(DeliveryPackage deliveryPackage) {
        initComponents();

        this.delPackage = deliveryPackage;

        displayProductList();
        
        displayPackageDetails();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        custIDJLabel = new javax.swing.JLabel();
        custIDTxtField = new javax.swing.JTextField();
        custNameJLabel = new javax.swing.JLabel();
        custNameTxtField = new javax.swing.JTextField();
        packageIDJLabel = new javax.swing.JLabel();
        packageIDTxtField = new javax.swing.JTextField();
        packageWeightJLabel = new javax.swing.JLabel();
        packageWeightTxtField = new javax.swing.JTextField();
        updateJButton = new javax.swing.JButton();
        productComboBox = new javax.swing.JComboBox();
        showButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        prodIDJLabel = new javax.swing.JLabel();
        prodPriceTxtField = new javax.swing.JTextField();
        prodPriceJLabel = new javax.swing.JLabel();
        prodIDTxtField = new javax.swing.JTextField();
        prodNameJLabel = new javax.swing.JLabel();
        prodNameTxtField = new javax.swing.JTextField();
        updateProductJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        custIDJLabel.setText("Customer ID");

        custIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDTxtFieldActionPerformed(evt);
            }
        });

        custNameJLabel.setText("Customer Name");

        custNameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custNameTxtFieldFocusLost(evt);
            }
        });
        custNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameTxtFieldActionPerformed(evt);
            }
        });

        packageIDJLabel.setText("Package ID");

        packageIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageIDTxtFieldActionPerformed(evt);
            }
        });

        packageWeightJLabel.setText("Package Weight");

        packageWeightTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWeightTxtFieldActionPerformed(evt);
            }
        });

        updateJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        updateJButton.setText("UPDATE");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        productComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productComboBoxActionPerformed(evt);
            }
        });

        showButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        showButton.setText("SHOW");
        showButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showButton)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(custNameJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(packageWeightJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(packageWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(packageIDJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(packageIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(custIDJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(updateJButton)
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custIDJLabel)
                    .addComponent(custIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(custNameJLabel)
                    .addComponent(custNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageIDJLabel)
                    .addComponent(packageIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageWeightJLabel)
                    .addComponent(packageWeightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(updateJButton)
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showButton))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));

        prodIDJLabel.setText("Product ID");

        prodPriceTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodPriceTxtFieldActionPerformed(evt);
            }
        });

        prodPriceJLabel.setText("Product Price");

        prodIDTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                prodIDTxtFieldFocusLost(evt);
            }
        });
        prodIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodIDTxtFieldActionPerformed(evt);
            }
        });

        prodNameJLabel.setText("Product Name");

        prodNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodNameTxtFieldActionPerformed(evt);
            }
        });

        updateProductJButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        updateProductJButton.setText("UPDATE PRODUCT");
        updateProductJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prodPriceJLabel)
                    .addComponent(prodIDJLabel)
                    .addComponent(prodNameJLabel))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(prodPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(28, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(updateProductJButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodIDJLabel)
                    .addComponent(prodIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodNameJLabel)
                    .addComponent(prodNameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodPriceJLabel)
                    .addComponent(prodPriceTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132)
                .addComponent(updateProductJButton)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jSplitPane2.setRightComponent(jPanel4);

        jPanel1.add(jSplitPane2);

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void custIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDTxtFieldActionPerformed

    private void custNameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameTxtFieldFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_custNameTxtFieldFocusLost

    private void custNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameTxtFieldActionPerformed

    private void packageIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageIDTxtFieldActionPerformed

    private void packageWeightTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWeightTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWeightTxtFieldActionPerformed

    private void prodPriceTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodPriceTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodPriceTxtFieldActionPerformed

    private void prodIDTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prodIDTxtFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_prodIDTxtFieldFocusLost

    private void prodIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodIDTxtFieldActionPerformed

    private void prodNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodNameTxtFieldActionPerformed

    private void productComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productComboBoxActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:

        // get the data
        String id = packageIDTxtField.getText();
        String weight = packageWeightTxtField.getText();
//        String productId = productId1.getText();
//        String productName = productName1.getText();
//        String productPrice = productPrice1.getText();
        String customerId = custIDTxtField.getText();
        String customername = custNameTxtField.getText();

        // store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));

        Customer customer = this.delPackage.getCustomer();
        customer.setCustId(Integer.valueOf(customerId));
        customer.setFullName(customername);
        
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void updateProductJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductJButtonActionPerformed
        // TODO add your handling code here:
        
        
        // update the product in the list
        this.productViewed.setProductName(prodNameTxtField.getText());
        this.productViewed.setPrice(Double.valueOf(prodPriceTxtField.getText()));
        
        
    }//GEN-LAST:event_updateProductJButtonActionPerformed

    private void showButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showButtonActionPerformed
        // TODO add your handling code here:
        
        // to disable the field
        prodIDTxtField.setEnabled(false);
        
        int pid = (int) productComboBox.getSelectedItem();

        // find the product in the arraylsit
        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) {
            prodIDTxtField.setText(String.valueOf(pid));
            prodNameTxtField.setText(prod.getProductName());
            prodPriceTxtField.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }

    }//GEN-LAST:event_showButtonActionPerformed
    public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            productComboBox.addItem(p.getProductId());
        }

    }

    public void displayPackageDetails() {
        packageIDTxtField.setText(String.valueOf(this.delPackage.getPackageId()));
        packageWeightTxtField.setText(String.valueOf(this.delPackage.getPackageWeight()));

        Customer customer = this.delPackage.getCustomer();
        custIDTxtField.setText(String.valueOf(customer.getCustId()));
        custNameTxtField.setText(customer.getFullName());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custIDJLabel;
    private javax.swing.JTextField custIDTxtField;
    private javax.swing.JLabel custNameJLabel;
    private javax.swing.JTextField custNameTxtField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel packageIDJLabel;
    private javax.swing.JTextField packageIDTxtField;
    private javax.swing.JLabel packageWeightJLabel;
    private javax.swing.JTextField packageWeightTxtField;
    private javax.swing.JLabel prodIDJLabel;
    private javax.swing.JTextField prodIDTxtField;
    private javax.swing.JLabel prodNameJLabel;
    private javax.swing.JTextField prodNameTxtField;
    private javax.swing.JLabel prodPriceJLabel;
    private javax.swing.JTextField prodPriceTxtField;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JButton showButton;
    private javax.swing.JButton updateJButton;
    private javax.swing.JButton updateProductJButton;
    // End of variables declaration//GEN-END:variables
}
