/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Application;
import javax.swing.JSplitPane;

/**
 *
 * @author forumkaria
 */
public
        class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Application application;
    
    public
            MainJFrame() {
        initComponents();
        
        this.application = new Application();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        assignMedButton = new javax.swing.JButton();
        createObsButton = new javax.swing.JButton();
        viewVitalSignButton = new javax.swing.JButton();
        medCatalogButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(153, 153, 255));

        controlJPanel.setBackground(new java.awt.Color(204, 204, 255));
        controlJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        assignMedButton.setText("ASSIGN MEDICINES");
        assignMedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignMedButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(assignMedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 180, -1));

        createObsButton.setText("CREATE OBSERVATION");
        createObsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createObsButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(createObsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, -1));

        viewVitalSignButton.setText("VIEW VITALSIGN HISTORY");
        viewVitalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewVitalSignButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(viewVitalSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, 30));

        medCatalogButton.setText("MEDICINE CATALOG");
        medCatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medCatalogButtonActionPerformed(evt);
            }
        });
        controlJPanel.add(medCatalogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 30));

        jSplitPane1.setLeftComponent(controlJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createObsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createObsButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateJPanel(this.application));
    }//GEN-LAST:event_createObsButtonActionPerformed

    private void viewVitalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewVitalSignButtonActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new ViewJPanel(this.application));
    }//GEN-LAST:event_viewVitalSignButtonActionPerformed

    private void medCatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medCatalogButtonActionPerformed
        // TODO add your handling code here:
         jSplitPane1.setRightComponent(new CatalogJPanel(this.application));
    }//GEN-LAST:event_medCatalogButtonActionPerformed

    private void assignMedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignMedButtonActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedAssignJPanel(this.application));
    }//GEN-LAST:event_assignMedButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignMedButton;
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton createObsButton;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton medCatalogButton;
    private javax.swing.JButton viewVitalSignButton;
    // End of variables declaration//GEN-END:variables
}
