/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author forumkaria
 */
public
        class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public Person person = new Person();
    
    public
            MainJFrame() {
        initComponents();
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        createBtn = new javax.swing.JButton();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        currentAddJLabel = new javax.swing.JLabel();
        colNameJLabel = new javax.swing.JLabel();
        personalPhoneNumJLabel = new javax.swing.JLabel();
        workPhoneJLabel = new javax.swing.JLabel();
        nuidJLabel = new javax.swing.JLabel();
        createFirstNameTxt = new javax.swing.JTextField();
        createPersonalPhoneTxt = new javax.swing.JTextField();
        createLastNameTxt = new javax.swing.JTextField();
        createWorkPhoneTxt = new javax.swing.JTextField();
        createPersEmailTxt = new javax.swing.JTextField();
        createCurrStreetTxt = new javax.swing.JTextField();
        createCurrAptTxt = new javax.swing.JTextField();
        createCurrCityTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        createIdTextField = new javax.swing.JTextField();
        permAddJLabel = new javax.swing.JLabel();
        streetJLabel = new javax.swing.JLabel();
        zipJLabel = new javax.swing.JLabel();
        aptNoJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        stateJLabel = new javax.swing.JLabel();
        createCurrZipTxt = new javax.swing.JTextField();
        createCurrStateTxt = new javax.swing.JTextField();
        personalEmailJLabel = new javax.swing.JLabel();
        workEmailJLabel = new javax.swing.JLabel();
        createColNameTxt = new javax.swing.JTextField();
        createWorkEmailTxt = new javax.swing.JTextField();
        createPermAptTxt = new javax.swing.JTextField();
        streetJLabel2 = new javax.swing.JLabel();
        createPermStreetTxt = new javax.swing.JTextField();
        aptNoJLabel2 = new javax.swing.JLabel();
        cityJLabel2 = new javax.swing.JLabel();
        createPermCityTxt = new javax.swing.JTextField();
        stateJLabel2 = new javax.swing.JLabel();
        createPermStateTxt = new javax.swing.JTextField();
        zipJLabel2 = new javax.swing.JLabel();
        createPermZipTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        huskyCardJLabel = new javax.swing.JLabel();
        viewNuid = new javax.swing.JTextField();
        viewFirstNameTxt = new javax.swing.JTextField();
        viewLastNameTxt = new javax.swing.JTextField();
        viewPersonalPhoneTxt = new javax.swing.JTextField();
        viewWorkPhoneTxt = new javax.swing.JTextField();
        viewPersEmailTxt = new javax.swing.JTextField();
        viewWorkEmailTxt = new javax.swing.JTextField();
        viewColNameTxt = new javax.swing.JTextField();
        viewCurrStreetTxt = new javax.swing.JTextField();
        viewCurrAptTxt = new javax.swing.JTextField();
        viewPermStreetTxt = new javax.swing.JTextField();
        viewPermAptTxt = new javax.swing.JTextField();
        viewCurrCityTxt = new javax.swing.JTextField();
        viewCurrStateTxt = new javax.swing.JTextField();
        viewCurrZipTxt = new javax.swing.JTextField();
        viewPermCityTxt = new javax.swing.JTextField();
        viewPermStateTxt = new javax.swing.JTextField();
        viewPermZipTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setResizeWeight(0.5);
        jSplitPane2.setAutoscrolls(true);
        jSplitPane2.setSize(new java.awt.Dimension(500, 0));

        jPanel1.setMinimumSize(new java.awt.Dimension(500, 50));

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        firstNameJLabel.setText("First Name:");

        lastNameJLabel.setText("Last Name:");

        currentAddJLabel.setText("Current Address:");

        colNameJLabel.setText("College Name:");

        personalPhoneNumJLabel.setText("Personal Phone:");

        workPhoneJLabel.setText("Work Phone:");

        nuidJLabel.setText("NU ID:");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("Create Student");

        permAddJLabel.setText("Permanent Address:");

        streetJLabel.setText("Street:");

        zipJLabel.setText("Zip Code:");

        aptNoJLabel.setText("Apt No.:");

        cityJLabel.setText("City:");

        stateJLabel.setText("State:");

        personalEmailJLabel.setText("Personal Email:");

        workEmailJLabel.setText("Work Email:");

        streetJLabel2.setText("Street:");

        aptNoJLabel2.setText("Apt No.:");

        cityJLabel2.setText("City:");

        stateJLabel2.setText("State:");

        zipJLabel2.setText("Zip Code:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nuidJLabel)
                                .addComponent(personalEmailJLabel)
                                .addComponent(firstNameJLabel)
                                .addComponent(lastNameJLabel)
                                .addComponent(personalPhoneNumJLabel)
                                .addComponent(workPhoneJLabel)
                                .addComponent(workEmailJLabel)
                                .addComponent(colNameJLabel))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(currentAddJLabel)
                                .addGap(8, 8, 8)))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(streetJLabel)
                            .addComponent(stateJLabel)
                            .addComponent(cityJLabel)
                            .addComponent(aptNoJLabel)
                            .addComponent(zipJLabel))
                        .addGap(75, 75, 75)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createPersEmailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createWorkPhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createPersonalPhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createLastNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createFirstNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createIdTextField)
                            .addComponent(createColNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createWorkEmailTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createCurrZipTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(createCurrStateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createCurrCityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createCurrAptTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createCurrStreetTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(86, 86, 86)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetJLabel2)
                                    .addComponent(stateJLabel2)
                                    .addComponent(cityJLabel2)
                                    .addComponent(aptNoJLabel2)
                                    .addComponent(zipJLabel2))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(createPermZipTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createPermStateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createPermCityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createPermAptTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createPermStreetTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(permAddJLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel9)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(nuidJLabel)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createFirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameJLabel)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(createIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameJLabel)
                            .addComponent(createLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personalPhoneNumJLabel)
                            .addComponent(createPersonalPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workPhoneJLabel)
                            .addComponent(createWorkPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(personalEmailJLabel)
                            .addComponent(createPersEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(workEmailJLabel)
                            .addComponent(createWorkEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colNameJLabel)
                            .addComponent(createColNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentAddJLabel)
                            .addComponent(permAddJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createCurrStreetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createCurrAptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aptNoJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityJLabel)
                            .addComponent(createCurrCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateJLabel)
                            .addComponent(createCurrStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipJLabel)
                            .addComponent(createCurrZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createPermStreetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(streetJLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createPermAptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(aptNoJLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityJLabel2)
                            .addComponent(createPermCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stateJLabel2)
                            .addComponent(createPermStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipJLabel2)
                            .addComponent(createPermZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane2.setLeftComponent(jPanel1);

        jPanel2.setMaximumSize(new java.awt.Dimension(356, 356));

        huskyCardJLabel.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        huskyCardJLabel.setText("Husky Card Details");

        viewColNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewColNameTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(huskyCardJLabel)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewPersEmailTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewWorkPhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPersonalPhoneTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewLastNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewFirstNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewNuid)
                            .addComponent(viewColNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewWorkEmailTxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewCurrZipTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                .addComponent(viewCurrStateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewCurrCityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewCurrAptTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewCurrStreetTxt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(221, 221, 221)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(viewPermZipTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewPermStateTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewPermCityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewPermAptTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(viewPermStreetTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(65, 65, 65)))
                    .addGap(98, 98, 98)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(huskyCardJLabel)
                .addContainerGap(675, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(viewFirstNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addComponent(viewNuid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(viewLastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(viewPersonalPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewWorkPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewPersEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewWorkEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewColNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(91, 91, 91)
                            .addComponent(viewCurrStreetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewCurrAptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewCurrCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewCurrStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewCurrZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(447, 447, 447)
                            .addComponent(viewPermStreetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewPermAptTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewPermCityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewPermStateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewPermZipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(52, Short.MAX_VALUE)))
        );

        jSplitPane2.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        String firstName = createFirstNameTxt.getText();
        String lastName = createLastNameTxt.getText();
        String nuid = createIdTextField.getText();
        String colName = createColNameTxt.getText();
        String curr_street = createCurrStreetTxt.getText();
        String perm_street = createPermStreetTxt.getText();
        String curr_apt_no = createCurrAptTxt.getText();
        String perm_apt_no = createPermAptTxt.getText();
        String curr_city = createCurrCityTxt.getText();
        String perm_city = createPermCityTxt.getText();
        String curr_state = createCurrStateTxt.getText();
        String perm_state = createPermStateTxt.getText();
        String pers_email = createPersEmailTxt.getText();
        String work_email = createWorkEmailTxt.getText();
        long personalPhone = Long.valueOf(createPersonalPhoneTxt.getText());
        long officePhone = Long.valueOf(createWorkPhoneTxt.getText());
        int curr_zip = Integer.valueOf(createCurrZipTxt.getText());
        int perm_zip = Integer.valueOf(createPermZipTxt.getText());
        
        Address curr_address = this.person.getCurrentAddress();
        Address perm_address = this.person.getPermanentAddress();

        Contact personalContact = this.person.getPersonalContact();
        Contact officeContact = this.person.getWorkContact();
        
        this.person.setFirstName(firstName);
        this.person.setLastName(lastName);
        this.person.setCollegeName(colName);
        this.person.setNuid(nuid);

        curr_address.setStreet(curr_street);
        curr_address.setAptNum(curr_apt_no);
        curr_address.setCity(curr_city);
        curr_address.setState(curr_state);
        curr_address.setZipcode(curr_zip);
        
        
        perm_address.setStreet(perm_street);
        perm_address.setAptNum(perm_apt_no);
        perm_address.setCity(perm_city);
        perm_address.setState(perm_state);
        perm_address.setZipcode(perm_zip);
        
        personalContact.setEmailID(pers_email);
        personalContact.setPhoneNumber(personalPhone);
        
        officeContact.setEmailID(work_email);
        officeContact.setPhoneNumber(officePhone);
        
        display();
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void display() {
        viewFirstNameTxt.setText(this.person.getFirstName());
        viewLastNameTxt.setText(this.person.getLastName());
        viewColNameTxt.setText(this.person.getCollegeName());
        viewNuid.setText(this.person.getNuid());

        viewCurrStreetTxt.setText(this.person.getCurrentAddress().getStreet());
        viewCurrAptTxt.setText(this.person.getCurrentAddress().getAptNum());
        viewCurrCityTxt.setText(this.person.getCurrentAddress().getCity());
        viewCurrStateTxt.setText(this.person.getCurrentAddress().getState());
        viewCurrZipTxt.setText(String.valueOf(this.person.getCurrentAddress().getZipcode()));
        
        viewPermStreetTxt.setText(this.person.getPermanentAddress().getStreet());
        viewPermAptTxt.setText(this.person.getPermanentAddress().getAptNum());
        viewPermCityTxt.setText(this.person.getPermanentAddress().getCity());
        viewPermStateTxt.setText(this.person.getPermanentAddress().getState());
        viewPermZipTxt.setText(String.valueOf(this.person.getPermanentAddress().getZipcode()));
        
        viewPersonalPhoneTxt.setText(String.valueOf(this.person.getPersonalContact().getPhoneNumber()));
        viewWorkPhoneTxt.setText(String.valueOf(this.person.getWorkContact().getPhoneNumber()));       
        viewPersEmailTxt.setText(this.person.getPersonalContact().getEmailID());
        viewWorkEmailTxt.setText(this.person.getWorkContact().getEmailID());

    }
    
    private void viewColNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewColNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewColNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static
            void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public
                    void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aptNoJLabel;
    private javax.swing.JLabel aptNoJLabel2;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel cityJLabel2;
    private javax.swing.JLabel colNameJLabel;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField createColNameTxt;
    private javax.swing.JTextField createCurrAptTxt;
    private javax.swing.JTextField createCurrCityTxt;
    private javax.swing.JTextField createCurrStateTxt;
    private javax.swing.JTextField createCurrStreetTxt;
    private javax.swing.JTextField createCurrZipTxt;
    private javax.swing.JTextField createFirstNameTxt;
    private javax.swing.JTextField createIdTextField;
    private javax.swing.JTextField createLastNameTxt;
    private javax.swing.JTextField createPermAptTxt;
    private javax.swing.JTextField createPermCityTxt;
    private javax.swing.JTextField createPermStateTxt;
    private javax.swing.JTextField createPermStreetTxt;
    private javax.swing.JTextField createPermZipTxt;
    private javax.swing.JTextField createPersEmailTxt;
    private javax.swing.JTextField createPersonalPhoneTxt;
    private javax.swing.JTextField createWorkEmailTxt;
    private javax.swing.JTextField createWorkPhoneTxt;
    private javax.swing.JLabel currentAddJLabel;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JLabel huskyCardJLabel;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JLabel nuidJLabel;
    private javax.swing.JLabel permAddJLabel;
    private javax.swing.JLabel personalEmailJLabel;
    private javax.swing.JLabel personalPhoneNumJLabel;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JLabel stateJLabel2;
    private javax.swing.JLabel streetJLabel;
    private javax.swing.JLabel streetJLabel2;
    private javax.swing.JTextField viewColNameTxt;
    private javax.swing.JTextField viewCurrAptTxt;
    private javax.swing.JTextField viewCurrCityTxt;
    private javax.swing.JTextField viewCurrStateTxt;
    private javax.swing.JTextField viewCurrStreetTxt;
    private javax.swing.JTextField viewCurrZipTxt;
    private javax.swing.JTextField viewFirstNameTxt;
    private javax.swing.JTextField viewLastNameTxt;
    private javax.swing.JTextField viewNuid;
    private javax.swing.JTextField viewPermAptTxt;
    private javax.swing.JTextField viewPermCityTxt;
    private javax.swing.JTextField viewPermStateTxt;
    private javax.swing.JTextField viewPermStreetTxt;
    private javax.swing.JTextField viewPermZipTxt;
    private javax.swing.JTextField viewPersEmailTxt;
    private javax.swing.JTextField viewPersonalPhoneTxt;
    private javax.swing.JTextField viewWorkEmailTxt;
    private javax.swing.JTextField viewWorkPhoneTxt;
    private javax.swing.JLabel workEmailJLabel;
    private javax.swing.JLabel workPhoneJLabel;
    private javax.swing.JLabel zipJLabel;
    private javax.swing.JLabel zipJLabel2;
    // End of variables declaration//GEN-END:variables
}
